name: Docker build -> push -> deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Jar
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t abdouaziz22/spring-boot-deploymentci:latest .

      - name: Push Image to Docker Hub
        run: docker push abdouaziz22/spring-boot-deploymentci:latest

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop spring-deploymentci || true
            docker rm spring-deploymentci || true
            docker rmi abdouaziz22/spring-boot-deploymentci:latest || true
            docker pull abdouaziz22/spring-boot-deploymentci:latest
            docker run -d \
              --name spring-deploymentci \
              -p 8080:8080 \
              abdouaziz22/spring-boot-deploymentci:latest
